services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: ironsakit
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"  # Postgre mette 5432 come porta ma meglio cambiarla perchè magari qualche altro servizio la sta già usando
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: